# Generated by Django 2.2.6 on 2020-04-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coustomer',
            new_name='Customer',
        ),
    ]
