# Generated by Django 2.2.6 on 2020-04-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_auto_20200419_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('Out of delivery', 'Out of delivery'), ('Delivered', 'Delivered')], max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(blank=True, choices=[('indoor', 'indoor'), ('Out Door', 'Out Door')], max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('product_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
