# Generated by Django 2.2.6 on 2020-04-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_auto_20200419_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='tag_name',
        ),
        migrations.AddField(
            model_name='product',
            name='tag_name',
            field=models.ManyToManyField(to='acc.Tag'),
        ),
    ]
