# Generated by Django 2.2.6 on 2020-04-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_auto_20200419_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=250, null=True),
        ),
    ]
