# Generated by Django 2.2 on 2020-10-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0007_auto_20201006_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
