# Generated by Django 2.2 on 2020-10-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0008_auto_20201006_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
