# Generated by Django 2.2 on 2020-10-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0006_auto_20200501_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Out of delivery', 'Out of delivery'), ('Delivered', 'Delivered')], default='pending', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], default='indoor', max_length=250, null=True),
        ),
    ]
